### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by Mara-Li** [OwnJoke/obsidian-budget-wysiwyg#1]
Some suggestion for this plugin :
- Add a way to indicate the place of the cursor in edit mode and change the cursor place when we click on a place.
- Add a way to adjust the timer between change edit/preview mode

**Comment by OwnJoke** [comment]
Not sure what you mean with the first point, if you are talking about the cursor saving between edit and preview, it already does that. And for the second point, that is a planned feature that I will probably add soon (Though I am leaving for a few weeks soon so I'm not sure when I will get around to adding it)

**Comment by Mara-Li** [comment]
For the first point : I remark that you can't see your cursor move, so when the switching happened you can't saw where you stop.

**Comment by AngelusDomini** [comment]
Regarding the first point: indeed, you can't see where the cursor is when you first open a note, you'd have to start typing in order to see. At first, I was clicking on the text in preview mode exactly where I wanted to type—which is what we always do in edit mode, but instead it was typing where my cursor was the last time I opened the note rather than where I want it now, if that makes sense. The current workaround would be to type something, delete the text, and then move the cursor in edit mode to where desired.

What was suggested by Mara is for a way to know where the cursor is currently located while in preview mode, and then have a way to change that location before typing by clicking on the desired location in preview mode, similar to what we already do in edit mode.

**Comment by OwnJoke** [comment]
Alright I get what you mean, I am not sure how exactly I would do that but I will try and figure it out

**Comment by crazymedguy** [comment]
Second this... Would be nice to be able to automatically switch to edit mode when clicking! Also, when clicking, shifting the cursor to wherever we have clicked. This would be a really nice touch because currently it has some friction in how we can switch to edit mode.

**Comment by OwnJoke** [comment]
Sure I could make clicking toggle to edit mode, I should probably add a setting for that as not everyone would want that. First I need to actually figure out how I would turn normal click coordinates into line and char.

**Comment by KALKI-the-avataar** [comment]
Simple Clicking can conflict when clicking a link instead something like alt + click would be better

**Comment by OwnJoke** [comment]
I'll probably leave it as a single click but ill make links still work. I am leaving tomorrow for a few weeks so the update probably won't be out for a while (unless i finish it today)
